services:
  dbclient:
    image: postgres
    environment:
      POSTGRES_DB: dbc
      POSTGRES_USER: dbclientuser
      POSTGRES_PASSWORD: dbclientpassword
    volumes:
      - ./serviceClient/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  dbbanque:
    image: postgres
    environment:
      POSTGRES_DB: dbb
      POSTGRES_USER: dbbanqueuser
      POSTGRES_PASSWORD: dbbanquepassword
    volumes:
      - ./serviceBanque/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
  serviceclient:
    build: ./serviceClient
    ports:
      - "8080:8080"
    depends_on:
      - dbclient

  servicebanque:
    build: ./serviceBanque
    ports:
      - "8081:8081"
    depends_on:
      - dbbanque
