{
 "title": "Dashboard metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Banque request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "banque_request_duration_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Client request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "client_request_duration_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Banque response size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "banque_http_response_size_bytes_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Client response size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "client_http_response_size_bytes_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram debit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "banque_debit_amount_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "DB Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "client_db_active_connections", "legendFormat": "{{environment}}" },
    { "expr": "banque_db_active_connections", "legendFormat": "{{environment}}" }
   ]
  }
 ]
}