{
 "title": "MGL870 TP1 Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Service banque", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service banque logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `serviceBanque`"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "banque_http_request_valid", "legendFormat": "HTTP 200" },
    { "expr": "banque_http_request_bad", "legendFormat": "HTTP 400" },
    { "expr": "banque_http_request_notfound", "legendFormat": "HTTP 404" },
    { "expr": "banque_http_request_error", "legendFormat": "HTTP 500" }
   ]
  },
  {
   "title": "Logs 500",
   "type": "logs",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `ERROR` |= `serviceBanque`"
    }
   ]
  },
  { "title": "Service client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service client logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `serviceClient`"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "client_http_request_valid", "legendFormat": "HTTP 200" },
    { "expr": "client_http_request_notfound", "legendFormat": "HTTP 404" },
    { "expr": "client_http_request_error", "legendFormat": "HTTP 500" }
   ]
  },
  {
   "title": "Logs 500",
   "type": "logs",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `ERROR` |= `serviceClient`"
    }
   ]
  }
 ]
}