global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'minishake972@gmail.com'
  smtp_auth_username: 'minishake972'
  smtp_auth_password: 'Kyllian971'

route:
  group_by: ['alertname']
  receiver: 'email-alerts'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'Klautric@gmail.com'
