groups:
  - name: microservice_alerts
    rules:

      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down"
          description: "L'instance {{ $labels.instance }} est hors service depuis plus d'1 minute."

      - alert: HighContainerCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{instance=~"$host",name=~"$container",name=~".+"}[5m])) by (name) * 100 > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on container {{ $labels.name }}"
          description: "The container {{ $labels.name }} has been using more than 80% CPU for more than 5 minutes."

      - alert: HighContainerMemoryUsage
        expr: sum(container_memory_rss{instance=~"$host",name=~"$container",name=~".+"}) by (name) > 500 * 1024 * 1024
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage on container {{ $labels.name }}"
          description: "The container {{ $labels.name }} has been using more than 500MB of memory for more than 5 minutes."

      - alert: HighDatabaseCPUUsage
        expr: avg(rate(process_cpu_seconds_total{release="$release", instance="$instance"}[10s]) * 1000) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "The CPU usage for release {{ $labels.release }} on instance {{ $labels.instance }} has exceeded 80% for the past minute."

      - alert: HighDatabaseRAMUsage
        expr: avg(rate(process_resident_memory_bytes{release="$release", instance="$instance"}[10s])) > 1e9  # 1 GB
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Resident Memory Usage"
          description: "The resident memory usage for release {{ $labels.release }} on instance {{ $labels.instance }} has exceeded 1 GB for more than 2 minutes."

      - alert: HighDatabaseOpenFileDescriptors
        expr: process_open_fds{release="$release", instance="$instance"} > 5000  # Seuil à ajuster en fonction de la capacité de votre système
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High number of open file descriptors"
          description: "The process {{ $labels.release }} on instance {{ $labels.instance }} has more than 5000 open file descriptors for more than 2 minutes."

      - alert: ClientRequestDurationHigh
        expr: histogram_quantile(0.95, sum(rate(client_request_duration_bucket[10s])) by (le)) > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Client Request Duration"
          description: "The 95th percentile of client request duration has exceeded 2 seconds for more than 5 minutes."

      - alert: ClientHttpRequestError
        expr: rate(client_http_request_error[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Client HTTP Request Errors Detected"
          description: "There have been HTTP request errors for the client in the last 5 minutes."

      - alert: BankRequestDurationHigh
        expr: histogram_quantile(0.95, sum(rate(banque_request_duration_bucket[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Bank Request Duration"
          description: "The 95th percentile of bank request duration has exceeded 2 seconds for more than 5 minutes."

      - alert: BankHttpRequestError
        expr: rate(banque_http_request_error[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Bank HTTP Request Errors Detected"
          description: "There have been HTTP request errors for the bank in the last 5 minutes."

      - alert: BankDebitAmountHigh
        expr: histogram_quantile(0.95, sum(rate(banque_debit_amount_bucket[5m])) by (le)) > 10000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Bank Debit Amount"
          description: "The 95th percentile of bank debit amount has exceeded $10,000 for more than 5 minutes."

      - alert: InactiveBanqueService
        expr: rate(banque_request_duration_bucket[5m]) == 0
        for: 5m
        labels:
          severity: informational
        annotations:
          summary: "Banque Service Inactive"
          description: "No requests have been processed by the Banque service in the last 15 minutes. This could indicate low usage."
